@startuml 
    component "Verifiable Credentials \n Azure Active Directory" as VC #OrangeRed
    Rectangle "Issuer Application" as ISS #SkyBlue
    Rectangle "MS Authenticator" as AUTH #SkyBlue
    Rectangle "Display Card \n Implement VC Rules" as DISPLAY #SkyBlue

    ISS -> AUTH : Specifies the VC that must be issued

    AUTH -> VC : Requests details of the required VC

    VC -> AUTH : Returns card display details and rules for geting claims

    DISPLAY -> VC : Supplies required claims values and requests VC

    VC -> DISPLAY : Returns VC
@enduml